export { Client } from './lib/Client'
export { Message } from './lib/Message'
export { PrivateMessage } from './lib/PrivateMessage'
export { QueuedMessage } from './lib/QueuedMessage'
export { Room } from './lib/Room'
export { RoomCollection } from './lib/RoomCollection'
export { RoomMessage } from './lib/RoomMessage'
export { User } from './lib/User'
export { UserCollection } from './lib/UserCollection'
export { Username } from './lib/Username'
export * as Utils from './lib/Utils'
export { SimpleEventDispatcher, EventDispatcher } from "strongly-typed-events";